"""
Analysis API — RedoClaim
Full IRDAI Hierarchy of Evidence implementation:
  Step 1: SLA violations
  Step 2: IRDAI regulatory violations (RAG-powered)
  Step 3: Redressal route determination
  
Plus: CIS scanner, portability advisor
"""
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.ext.asyncio import AsyncSession
from pydantic import BaseModel
from typing import Optional
from datetime import datetime
import logging

from app.core.database import get_db
from app.models.models import Document, Claim, InsuranceType, ClaimStatus, DocumentType
from app.services.llm.gemini_service import (
    audit_rejection, analyze_cis, generate_portability_guide
)
from app.services.rag.rag_pipeline import (
    search_irdai_regulations, search_rejection_patterns, search_policy_chunks
)
from app.services.irdai.rules_engine import irdai_engine
from app.api.deps.auth import get_current_user

router = APIRouter()

# ── AI Disclaimer (appended to all AI-generated responses) ────────
AI_DISCLAIMER = {
    "disclaimer": (
        "This analysis is AI-generated by a local language model and may contain errors, "
        "omissions, or inaccurate regulation citations. It is intended as a research "
        "starting point only. This is NOT legal advice. Always verify IRDAI regulation "
        "references at irdai.gov.in and consult a licensed insurance advocate before "
        "taking legal action. RedoClaim and its operators accept no liability for "
        "decisions made based on this output."
    ),
    "verify_at": "https://www.irdai.gov.in",
    "free_legal_aid": "Contact your nearest District Legal Services Authority (DLSA) for free legal help",
}

logger = logging.getLogger(__name__)


# ── 1. Main Audit Endpoint ────────────────────────────────────────
class AuditRequest(BaseModel):
    rejection_document_id: str
    policy_document_id: Optional[str] = None
    cis_document_id: Optional[str] = None
    insurer_name: str
    policy_number: str
    claim_amount: Optional[float] = None
    insurance_type: InsuranceType = InsuranceType.HEALTH
    claim_date: Optional[datetime] = None
    rejection_date: Optional[datetime] = None
    gro_filed: bool = False
    gro_filed_date: Optional[datetime] = None


@router.post("/audit-rejection")
async def audit_claim_rejection(
    req: AuditRequest,
    db: AsyncSession = Depends(get_db),
    current_user=Depends(get_current_user),
):
    """
    Full IRDAI-compliant rejection audit using Hierarchy of Evidence.
    RAG retrieves relevant IRDAI regulations from Qdrant in real-time.
    """
    # Fetch rejection letter
    rejection_doc = await db.get(Document, req.rejection_document_id)
    if not rejection_doc or str(rejection_doc.owner_id) != str(current_user.id):
        raise HTTPException(404, "Rejection document not found")
    if not rejection_doc.ocr_text:
        raise HTTPException(400, "Document still processing. Please wait and retry.")

    # Fetch policy clauses
    policy_clauses = {}
    policy_doc = None
    if req.policy_document_id:
        policy_doc = await db.get(Document, req.policy_document_id)
        if policy_doc and policy_doc.extracted_clauses:
            policy_clauses = policy_doc.extracted_clauses

    # Fetch CIS if provided
    cis_exclusions = []
    if req.cis_document_id:
        cis_doc = await db.get(Document, req.cis_document_id)
        if cis_doc and cis_doc.extracted_clauses:
            cis_data = cis_doc.extracted_clauses
            cis_exclusions = [
                e.get("exclusion", e.get("clause", ""))
                for e in cis_data.get("exclusions", [])
            ]

    # ── Step 1: SLA Check (rule-based, always runs first) ─────────
    gro_days_elapsed = 0
    if req.gro_filed and req.gro_filed_date:
        gro_days_elapsed = (datetime.now() - req.gro_filed_date).days

    sla_result = irdai_engine.check_sla_violations(
        claim_date=req.claim_date,
        rejection_date=req.rejection_date,
        grievance_date=req.gro_filed_date,
    )

    # ── Step 2: RAG — retrieve relevant IRDAI regulations ─────────
    rejection_category = irdai_engine.get_rejection_category(rejection_doc.ocr_text)
    rag_query = (
        f"{rejection_category} claim rejection "
        f"{req.insurance_type.value} insurance "
        f"{rejection_doc.ocr_text[:300]}"
    )
    irdai_context = await search_irdai_regulations(rag_query)
    rejection_patterns = await search_rejection_patterns(rejection_doc.ocr_text)

    # ── Step 2: LLM audit with full context ───────────────────────
    audit_result = await audit_rejection(
        rejection_text=rejection_doc.ocr_text,
        policy_clauses=policy_clauses,
        irdai_context=irdai_context,
        rejection_patterns=rejection_patterns,
    )

    # ── Step 2: Moratorium check ───────────────────────────────────
    moratorium = {"moratorium_applies": False}
    portability_advice = None
    if req.insurance_type == InsuranceType.HEALTH:
        policy_start = None
        inception = policy_clauses.get("inception_date")
        if inception:
            try:
                policy_start = datetime.fromisoformat(str(inception))
            except Exception:
                pass
        moratorium = irdai_engine.check_moratorium(
            policy_start_date=policy_start,
            rejection_reason=rejection_doc.ocr_text[:500],
        )
        # Portability advisor
        if policy_start:
            years_covered = (datetime.now() - policy_start).days / 365.25
            portability_advice = irdai_engine.portability_advisor(
                policy_clauses=policy_clauses,
                years_covered=years_covered,
            )

    # ── Step 2: CIS violation check ────────────────────────────────
    cis_check = irdai_engine.check_cis_violation(
        rejection_reason=rejection_doc.ocr_text,
        cis_exclusions=cis_exclusions,
    )

    # ── Step 2: Deficiency in Service determination ───────────────
    all_irdai_violations = audit_result.get("step2_regulatory_violations", [])
    rejection_appears_arbitrary = (
        not audit_result.get("is_valid_rejection", True)
        and audit_result.get("confidence") in ["high", "medium"]
    )
    deficiency = irdai_engine.check_deficiency_in_service(
        sla_violations=sla_result["sla_violations"],
        irdai_violations=all_irdai_violations,
        rejection_appears_arbitrary=rejection_appears_arbitrary,
    )

    # ── Step 3: Escalation path ────────────────────────────────────
    escalation = irdai_engine.determine_escalation_path(
        claim_amount=req.claim_amount,
        gro_filed=req.gro_filed,
        gro_days_elapsed=gro_days_elapsed,
        rejection_date=req.rejection_date,
    )

    # ── Assemble full report ───────────────────────────────────────
    full_report = {
        "hierarchy_of_evidence": {
            "step1_sla": sla_result,
            "step2_regulations": {
                "audit": audit_result,
                "moratorium": moratorium,
                "cis_check": cis_check,
                "deficiency_in_service": deficiency,
            },
            "step3_redressal": escalation,
        },
        "rejection_category": rejection_category,
        "portability_advice": portability_advice,
        "rag_context_used": bool(irdai_context),
        "generated_at": datetime.now().isoformat(),
    }

    # ── Save claim ─────────────────────────────────────────────────
    claim = Claim(
        owner_id=current_user.id,
        insurer_name=req.insurer_name,
        policy_number=req.policy_number,
        claim_amount=req.claim_amount,
        insurance_type=req.insurance_type,
        status=ClaimStatus.REJECTED,
        rejection_reason_raw=rejection_doc.ocr_text[:2000],
        rejection_reason_parsed={"category": rejection_category, "audit": audit_result},
        irdai_violation=bool(all_irdai_violations or sla_result["sla_violations"]),
        irdai_violation_details=all_irdai_violations,
        audit_report=full_report,
        claim_date=req.claim_date,
        rejection_date=req.rejection_date,
        gro_deadline=sla_result["deadlines"].get("gro_deadline"),
        irdai_deadline=sla_result["deadlines"].get("ombudsman_deadline"),
    )
    db.add(claim)
    await db.flush()

    total_violations = len(all_irdai_violations) + len(sla_result["sla_violations"])
    return {
        "claim_id": str(claim.id),
        "report": full_report,
        "ai_disclaimer": AI_DISCLAIMER,
        "summary": {
            "is_valid_rejection": audit_result.get("is_valid_rejection"),
            "total_violations_found": total_violations,
            "sla_violations": len(sla_result["sla_violations"]),
            "irdai_violations": len(all_irdai_violations),
            "strength_of_case": audit_result.get("strength_of_case"),
            "recommended_action": audit_result.get("step3_redressal", {}).get("recommended_action"),
            "moratorium_shield": moratorium.get("moratorium_applies", False),
            "deficiency_in_service": deficiency.get("deficiency_in_service", False),
            "cis_violation": cis_check.get("cis_violation", False),
            "interest_applicable": sla_result.get("interest_applicable", False),
            "edaakhil_applicable": escalation["escalation_path"][2].get("edaakhil_now_applicable", False),
        },
    }


# ── 2. CIS Scanner ────────────────────────────────────────────────
@router.post("/scan-cis/{document_id}")
async def scan_cis(
    document_id: str,
    db: AsyncSession = Depends(get_db),
    current_user=Depends(get_current_user),
):
    """
    Scan a Customer Information Sheet (CIS) document.
    IRDAI Master Circular 2024, Para 4.2: Insurer must provide CIS.
    Extracts all inclusions and exclusions in plain English.
    """
    doc = await db.get(Document, document_id)
    if not doc or str(doc.owner_id) != str(current_user.id):
        raise HTTPException(404, "Document not found")
    if not doc.ocr_text:
        raise HTTPException(400, "Document still processing.")

    cis_analysis = await analyze_cis(doc.ocr_text)

    # Update document with CIS analysis
    doc.extracted_clauses = cis_analysis
    doc.summary = (
        f"INCLUSIONS: {cis_analysis.get('plain_english_inclusions', 'N/A')} | "
        f"EXCLUSIONS: {cis_analysis.get('plain_english_exclusions', 'N/A')}"
    )
    await db.flush()

    return {
        "document_id": document_id,
        "cis_analysis": cis_analysis,
        "ai_disclaimer": AI_DISCLAIMER,
        "irdai_note": (
            "Under IRDAI Master Circular 2024, Para 4.2, your insurer CANNOT enforce "
            "any exclusion that is not clearly stated in this CIS."
        ),
    }


# ── 3. Policy Summary ─────────────────────────────────────────────
@router.get("/policy/{document_id}/summary")
async def get_policy_summary(
    document_id: str,
    db: AsyncSession = Depends(get_db),
    current_user=Depends(get_current_user),
):
    doc = await db.get(Document, document_id)
    if not doc or str(doc.owner_id) != str(current_user.id):
        raise HTTPException(404, "Document not found")
    if doc.ocr_status != "done":
        return {"status": "processing", "message": "Analysis in progress..."}
    return {
        "document_id": document_id,
        "file_name": doc.file_name,
        "is_cis": doc.extracted_clauses.get("is_cis", False) if doc.extracted_clauses else False,
        "extracted_clauses": doc.extracted_clauses,
        "risk_flags": doc.risk_flags,
        "summary": doc.summary,
    }


# ── 4. Portability Advisor ────────────────────────────────────────
class PortabilityRequest(BaseModel):
    policy_document_id: str
    years_covered: float
    reason_for_porting: str


@router.post("/portability-guide")
async def portability_guide(
    req: PortabilityRequest,
    db: AsyncSession = Depends(get_db),
    current_user=Depends(get_current_user),
):
    """
    Generate a personalised portability guide.
    IRDAI (Health Insurance) Regulations 2024, Regulation 17.
    """
    policy_clauses = {}
    doc = await db.get(Document, req.policy_document_id)
    if doc and doc.extracted_clauses:
        policy_clauses = doc.extracted_clauses

    guide_text = await generate_portability_guide(
        current_policy=policy_clauses,
        years_covered=req.years_covered,
        reason_for_porting=req.reason_for_porting,
    )

    engine_advice = irdai_engine.portability_advisor(
        policy_clauses=policy_clauses,
        years_covered=req.years_covered,
    )

    return {
        "ai_disclaimer": AI_DISCLAIMER,
        "portability_guide": guide_text,
        "key_rights": engine_advice["key_rights"],
        "how_to_port": engine_advice["how_to_port"],
        "regulation": engine_advice["regulation"],
    }


# ── 5. E-Daakhil Guide ────────────────────────────────────────────
@router.get("/edaakhil-guide")
async def edaakhil_guide():
    """
    Step-by-step guide to filing on e-Jagriti Consumer Court portal.
    Triggered when insurer doesn't respond within 15 days.
    """
    return {
        "portal": "e-jagriti.gov.in",
        "when_to_use": (
            "If your insurer has NOT responded to your complaint within 15 days, "
            "OR if you are unsatisfied with their response, you can file directly "
            "on the e-Jagriti Consumer Court portal."
        ),
        "legal_basis": "Consumer Protection Act 2019, Section 2(11) — Deficiency in Service",
        "steps": [
            {
                "step": 1,
                "action": "Register on e-Jagriti",
                "detail": "Go to e-jagriti.gov.in → Click 'Register' → Fill your details → Verify email",
            },
            {
                "step": 2,
                "action": "File a new complaint",
                "detail": (
                    "Click 'File Complaint' → Select 'Service' category → "
                    "Sub-category: 'Insurance' → Fill insurer details and policy number"
                ),
            },
            {
                "step": 3,
                "action": "Describe the deficiency",
                "detail": (
                    "Write: 'The respondent insurer has committed Deficiency in Service "
                    "as defined under Section 2(11) of the Consumer Protection Act, 2019 "
                    "by [specific acts]. This is in violation of IRDAI Master Circular 2024.'"
                ),
            },
            {
                "step": 4,
                "action": "Upload documents",
                "detail": (
                    "Upload: Policy document, rejection letter, GRO complaint copy, "
                    "hospital records, any correspondence with insurer"
                ),
            },
            {
                "step": 5,
                "action": "Pay court fee",
                "detail": (
                    "₹200 for claims up to ₹5 Lakhs | ₹400 for ₹5L–₹10L | "
                    "₹1,000 for ₹10L–₹20L | ₹2,000 for ₹20L–₹50L "
                    "(exact fees vary — check portal)"
                ),
            },
            {
                "step": 6,
                "action": "Submit and track",
                "detail": (
                    "You will receive a case number. Track hearing dates via email/SMS. "
                    "The commission typically schedules a hearing within 21 days."
                ),
            },
        ],
        "relief_you_can_claim": [
            "Full claim amount with interest (typically 9–12% per annum)",
            "Compensation for mental agony and harassment",
            "Cost of litigation",
            "Punitive damages in cases of gross insurer misconduct",
            "Product liability damages if policy was mis-sold",
        ],
        "important_notes": [
            "Limitation period: 2 years from the date of rejection",
            "No lawyer required — you can represent yourself",
            "Insurer must appear and respond within 30 days of notice",
            "If insurer fails to appear: ex-parte order can be passed",
        ],
    }