"""
Audit-trail PDF export — bundles a claim's policy summary, audit findings,
appeal letters, and timeline into one downloadable PDF, so a user can hand
one document to a lawyer, the Ombudsman, or a consumer forum instead of
screenshotting the app.

Uses ReportLab (free, open-source, no external API) over content already
generated by the existing OpenAI calls — zero new runtime cost per export.
"""
import io
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, HRFlowable
)


def _styles():
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name="RCTitle", fontSize=20, leading=24, spaceAfter=6,
                               textColor=colors.HexColor("#4F46E5"), fontName="Helvetica-Bold"))
    styles.add(ParagraphStyle(name="RCH2", fontSize=14, leading=18, spaceBefore=18, spaceAfter=8,
                               textColor=colors.HexColor("#1F2937"), fontName="Helvetica-Bold"))
    styles.add(ParagraphStyle(name="RCBody", fontSize=10, leading=15, textColor=colors.HexColor("#374151")))
    styles.add(ParagraphStyle(name="RCMeta", fontSize=9, leading=13, textColor=colors.HexColor("#6B7280")))
    styles.add(ParagraphStyle(name="RCLetter", fontSize=9.5, leading=14, fontName="Helvetica",
                               textColor=colors.HexColor("#1F2937")))
    return styles


def _safe(text, default="Not available") -> str:
    if text is None or text == "":
        return default
    return str(text).replace("\n", "<br/>")


def build_audit_trail_pdf(
    user_name: str,
    claim: dict,
    audit_report: dict | None,
    appeals: list[dict],
    timeline_events: list[dict],
) -> bytes:
    """
    claim: dict with policy_number, insurer_name, claim_amount, insurance_type,
           status, rejection_reason_raw, irdai_violation, claim_date,
           rejection_date, gro_deadline, irdai_deadline, patient_name
    appeals: list of {appeal_type, letter_content, submitted_at, outcome}
    timeline_events: list of {date, title, status} from the timeline endpoint
    """
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=2 * cm, rightMargin=2 * cm, topMargin=2 * cm, bottomMargin=2 * cm,
    )
    styles = _styles()
    story = []

    # ── Cover / summary ──────────────────────────────────────────
    story.append(Paragraph("RedoClaim — Case Audit Trail", styles["RCTitle"]))
    story.append(Paragraph(
        f"Generated {datetime.now().strftime('%d %B %Y, %I:%M %p')} for {_safe(user_name)}",
        styles["RCMeta"],
    ))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#E5E7EB"), spaceBefore=8, spaceAfter=14))

    patient_line = claim.get("patient_name") or "Self (account holder)"
    summary_rows = [
        ["Insurer", _safe(claim.get("insurer_name"))],
        ["Policy Number", _safe(claim.get("policy_number"))],
        ["Insurance Type", _safe(claim.get("insurance_type"), "Health").title()],
        ["Claim Amount", f"₹{claim.get('claim_amount'):,.0f}" if claim.get("claim_amount") else "Not available"],
        ["Patient", patient_line],
        ["Current Status", _safe(claim.get("status"), "Unknown").replace("_", " ").title()],
        ["Claim Filed", _safe(claim.get("claim_date"))],
        ["Rejected On", _safe(claim.get("rejection_date"))],
        ["GRO Deadline", _safe(claim.get("gro_deadline"))],
        ["IRDAI Ombudsman Deadline", _safe(claim.get("irdai_deadline"))],
    ]
    table = Table(summary_rows, colWidths=[5.5 * cm, 10 * cm])
    table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9.5),
        ("TEXTCOLOR", (0, 0), (-1, -1), colors.HexColor("#374151")),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("LINEBELOW", (0, 0), (-1, -2), 0.5, colors.HexColor("#F3F4F6")),
    ]))
    story.append(table)

    # ── Rejection reason ─────────────────────────────────────────
    story.append(Paragraph("Insurer's Stated Rejection Reason", styles["RCH2"]))
    story.append(Paragraph(_safe(claim.get("rejection_reason_raw")), styles["RCBody"]))

    # ── Audit findings ───────────────────────────────────────────
    if audit_report:
        story.append(Paragraph("Audit Findings", styles["RCH2"]))
        deficiency = audit_report.get("deficiency_statement")
        if deficiency:
            story.append(Paragraph(f"<b>Deficiency in Service:</b> {_safe(deficiency)}", styles["RCBody"]))
            story.append(Spacer(1, 6))

        violations = audit_report.get("step2_regulatory_violations") or []
        if violations:
            story.append(Paragraph("<b>IRDAI Regulatory Violations Found:</b>", styles["RCBody"]))
            for v in violations[:10]:
                text = v.get("description") if isinstance(v, dict) else str(v)
                reg = v.get("regulation") if isinstance(v, dict) else None
                line = f"• {_safe(text)}" + (f" <i>({reg})</i>" if reg else "")
                story.append(Paragraph(line, styles["RCBody"]))
            story.append(Spacer(1, 6))

        key_args = audit_report.get("key_arguments") or []
        if key_args:
            story.append(Paragraph("<b>Key Arguments:</b>", styles["RCBody"]))
            for a in key_args[:8]:
                story.append(Paragraph(f"• {_safe(a)}", styles["RCBody"]))

    # ── Timeline ──────────────────────────────────────────────────
    if timeline_events:
        story.append(Paragraph("Case Timeline", styles["RCH2"]))
        timeline_rows = [["Date", "Event", "Status"]]
        for ev in timeline_events:
            date_display = _safe(ev.get("date"), "")[:10]
            timeline_rows.append([date_display, _safe(ev.get("title")), _safe(ev.get("status"), "").title()])
        t = Table(timeline_rows, colWidths=[2.8 * cm, 9 * cm, 3.7 * cm])
        t.setStyle(TableStyle([
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#EEF2FF")),
            ("FONTSIZE", (0, 0), (-1, -1), 8.5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#E5E7EB")),
        ]))
        story.append(t)

    # ── Appeal letters (each on a fresh page) ────────────────────
    for appeal in appeals:
        story.append(PageBreak())
        appeal_type_label = str(appeal.get("appeal_type", "")).replace("_", " ").title()
        story.append(Paragraph(f"Appeal Letter — {appeal_type_label}", styles["RCH2"]))
        meta_bits = []
        if appeal.get("submitted_at"):
            meta_bits.append(f"Submitted: {appeal['submitted_at']}")
        if appeal.get("outcome"):
            meta_bits.append(f"Outcome: {str(appeal['outcome']).title()}")
        if meta_bits:
            story.append(Paragraph(" | ".join(meta_bits), styles["RCMeta"]))
            story.append(Spacer(1, 8))
        letter_text = _safe(appeal.get("letter_content"), "No letter content available")
        for para in letter_text.split("<br/><br/>") if "<br/><br/>" in letter_text else letter_text.split("\n\n"):
            if para.strip():
                story.append(Paragraph(para.strip(), styles["RCLetter"]))
                story.append(Spacer(1, 6))

    # ── Footer disclaimer ─────────────────────────────────────────
    story.append(PageBreak())
    story.append(Paragraph(
        "This document was compiled automatically by RedoClaim from AI-generated audit findings and "
        "appeal drafts. It is provided for your reference and to share with a lawyer, the Insurance "
        "Ombudsman, or a consumer forum — it is not itself legal advice, and all figures and citations "
        "should be independently verified before relying on them.",
        styles["RCMeta"],
    ))

    doc.build(story)
    return buf.getvalue()
