"""initial_schema

Revision ID: fdbdc474a9f1
Revises: 
Create Date: 2026-05-28 03:26:31.455058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdbdc474a9f1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('claim_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'documents', 'claims', ['claim_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_column('documents', 'claim_id')
    # ### end Alembic commands ###
